# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: stt签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - run: ls
    - run: cd stt-checkin
    - uses: EgorDm/gha-yarn-node-cache@v1
    - run: yarn install
    - run: node ./index.js
